name: C++ CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild SNOW2.0.slnx /p:Configuration=Debug /p:Platform=x64

    - name: Run Operational Tests
      run: .\x64\Debug\SNOW2.0.exe